"""initial schema

Revision ID: 51054842165d
Revises: 
Create Date: 2026-09-16 01:16:42.637346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51054842165d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', name='run_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlist_symbols',
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('cohort', sa.Enum('A', 'B', 'C', name='cohort'), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('action', sa.Enum('LONG_CALL', 'LONG_PUT', 'NO_TRADE', name='action'), nullable=False),
    sa.Column('contract_id', sa.String(length=64), nullable=True),
    sa.Column('reasoning', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('validator_status', sa.Enum('ACCEPTED', 'REJECTED', name='validator_status'), nullable=False),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['ticker'], ['watchlist_symbols.ticker'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', name='log_level'), nullable=False),
    sa.Column('component', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('quote', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('earnings_date', sa.Date(), nullable=True),
    sa.Column('news_headlines', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['ticker'], ['watchlist_symbols.ticker'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'ticker', name='uq_snapshot_run_ticker')
    )
    op.create_table('contract_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.String(length=64), nullable=False),
    sa.Column('contract_type', sa.Enum('CALL', 'PUT', name='contract_type'), nullable=False),
    sa.Column('strike', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('expiry', sa.Date(), nullable=False),
    sa.Column('bid', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('ask', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('open_interest', sa.Integer(), nullable=False),
    sa.Column('implied_vol', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('eligible', sa.Boolean(), nullable=False),
    sa.Column('ineligible_reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paper_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cohort', sa.Enum('A', 'B', 'C', name='cohort'), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.String(length=64), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('max_loss', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='position_status'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('close_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('close_reason', sa.Enum('HORIZON', 'PRE_EXPIRY', name='close_reason'), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('direction_correct', sa.Boolean(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['paper_positions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_id')
    )
    op.create_table('marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('mark_date', sa.Date(), nullable=False),
    sa.Column('bid', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['paper_positions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_id', 'mark_date', name='uq_mark_position_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marks')
    op.drop_table('evaluations')
    op.drop_table('paper_positions')
    op.drop_table('contract_snapshots')
    op.drop_table('snapshots')
    op.drop_table('run_logs')
    op.drop_table('decisions')
    op.drop_table('watchlist_symbols')
    op.drop_table('runs')
    # ### end Alembic commands ###
    # Autogenerate does not emit DROP TYPE for Postgres enums (they can be
    # shared across tables, e.g. "cohort"), so upgrade -> downgrade ->
    # upgrade would otherwise fail with "type already exists". Drop them
    # explicitly, after every table that references them is gone.
    for enum_name in (
        "run_status",
        "cohort",
        "action",
        "validator_status",
        "log_level",
        "contract_type",
        "position_status",
        "close_reason",
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
