"""add expiry to paper_positions

Revision ID: 8f3c893734fd
Revises: 51054842165d
Create Date: 2026-09-16 22:25:51.326372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f3c893734fd'
down_revision: Union[str, Sequence[str], None] = '51054842165d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_positions', sa.Column('expiry', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper_positions', 'expiry')
    # ### end Alembic commands ###
