"""add underlying prices to paper_positions

Revision ID: a83e07a2f20b
Revises: 8f3c893734fd
Create Date: 2026-09-16 22:47:36.447991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a83e07a2f20b'
down_revision: Union[str, Sequence[str], None] = '8f3c893734fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_positions', sa.Column('underlying_open', sa.Numeric(precision=12, scale=4), nullable=False))
    op.add_column('paper_positions', sa.Column('underlying_close', sa.Numeric(precision=12, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper_positions', 'underlying_close')
    op.drop_column('paper_positions', 'underlying_open')
    # ### end Alembic commands ###
